version: "3.8"
services: 
  php: 
    build: .
    # image: php:7.1-apache
    volumes: 
      - ./src:/var/www/html
    ports: 
      - 5080:80

  mysql:
    image: mysql:8
    ports: 
      - 3306:3306
    environment: 
      # MYSQL_USER: Quy
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      # MYSQL_ALLOW_EMPTY_PASSWORD: true

  php-admin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      # MYSQL_USER: Quy
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 8088:80